image: node:latest

before_script:
  - yarn
  - npm install -g gulp

build:
  script:
    - gulp build
  artifacts:
    paths:
      - build/js
      - build/css
  only:
    - master

pages:
  script:
    - gulp build
    - mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./build/ s3://srct/masonstrap/ --recursive
  only:
  - master
