image: node:latest

build:
  stage: build
  script:
    - apt-get update
    - apt-get install software-properties-common python-software-properties -y
    - add-apt-repository ppa:tista/build -y
    - apt-get update
    - apt-get install libsass -y 
    - yarn
    - npm run build-masonstrap
  artifacts:
    paths:
      - masonstrap/masonstrap.min.css
