image: node:7.6.0

build_css:
    before_script:
        - npm install
        - npm install -g grunt-cli
        - npm install -g bower
        - apt-get update
        - apt-get install ruby -y
        - gem install sass
        - bower install --allow-root
        - sass --version
    script:
        - grunt build
    artifacts:
        paths:
            - masonstrap/masonstrap.min.css

pages:
    stage: deploy
    script:
    - mkdir .public
    - cp index.html .public
    - cp bower_components/bootstrap/dist/js/bootstrap.min.js .public/bootstrap/dist/js
    - cp -r masonstrap .public
    - cp -r assets .public
    - mv .public public
    artifacts:
        paths:
        - public
