image: node:7.6.0

build_css:
    stage: deploy
    before_script:
        - npm install
        - npm install -g grunt-cli
        - npm install -g bower
        - apt-get update
        - apt-get install ruby -y
        - gem install sass
        - bower install --allow-root
    script:
        - grunt build
        - mkdir .public
        - cp index.html .public
        - cp -r ./bower_components/bootstrap/dist/js .public
        - cp -r ./masonstrap .public
        - cp -r ./assets .public
        - ls -laF .public
        - ls -laF .public/masonstrap
        - ls -laF .public/assets
        - ls -laF .public/bower_components/bootstrap/dist/js
        - mv .public public
    artifacts:
        paths:
            - public 
            - masonstrap/masonstrap.min.css
