image: node:7.6.0

build_css:
    before_script:
        - npm install
        - npm install -g grunt-cli
        - sudo apt-get install ruby-sass
    script:
        - grunt swatch
    artifacts:
        paths:
            - masonstrap/bootstrap.min.css

