image: node:7.6.0

build_css:
    before_script:
        - npm install
        - npm install bower
        - bower install
        - gem install sass
    script:
        - grunt swatch
    artifacts:
        paths:
            - masonstrap/bootstrap.min.css

