image: node:4.2.6

build_css:
    before_script:
        - npm install -g grunt-cli
        - npm install
    script:
        - grunt swatch:masonstrap
    artifacts:
        paths:
            - masonstrap/masonstrap.min.css

