image: node:latest

build:
  stage: build
  script:
    - yarn
    - npm run build-masonstrap
  artifacts:
    paths:
      - public/assets/css/masonstrap.min.css
      - public/assets/js/bootstrap.min.js
      - public/assets/js/jquery.min.js
      - public/assets/js/popper.min.js
      - public/assets/fonts/fontawesome-webfont.woff2
