image: node:latest

before_script:
  - yarn
  - npm install -g gulp

build:
  stage: build
  script:
    - gulp build
  artifacts:
    paths:
      - build/js
      - build/css
  only:
    - master

pages:
  stage: deploy
  script:
    - gulp build
    - mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
  only:
    - master
