image: node:4.2.6

build_css:
    before_script:
        - npm install -g grunt-cli
        - npm install
    script:
        - grunt swatch:masonstrap
    artifacts:
        paths:
            - masonstrap/masonstrap.min.css

pages:
    stage: deploy
    script:
    - mkdir .public
    - cp index.html masonstrap/masonstrap.min.css assets/css/custom.min.css bower_components/bootstrap/dist/js/bootstrap.min.js assets/js/custom.js .public
    - mv .public public
    artifacts:
        paths:
        - public
    only:
        - master
