image: node:latest

before_script:
  - npm i --save @fortawesome/fontawesome
  - yarn
  - yarn add @fortawesome/fontawesome-free-webfonts
  - npm install -g gulp

build:
  stage: build
  script:
    - gulp build
  artifacts:
    paths:
      - build/js
      - build/css
      - build/fonts
  only:
    - master

pages:
  stage: deploy
  script:
    - gulp build
    - mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
  only:
    - master
