image: node:latest

build:
  script:
    - yarn
    - npm install -g gulp
    - gulp build
  artifacts:
    paths:
      - build/js
      - build/css
  only:
    - master

pages:
  script:
    - yarn
    - npm install -g gulp
    - gulp build
    - mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  image: python:latest
  script:
  - pip install s3cmd 
  - s3cmd put ./build/css/ s3://srct/masonstrap/ --recursive --host='nyc3.digitaloceanspaces.com' --host-bucket='%(bucket)s.nyc3.digitaloceanspaces.com' --exclude='*' --include='*.min.css' --acl-public -m 'text/css'
  - s3cmd put ./build/js/ s3://srct/masonstrap/ --recursive --host='nyc3.digitaloceanspaces.com' --host-bucket='%(bucket)s.nyc3.digitaloceanspaces.com' --exclude='*' --include='*.min.js' --acl-public -m 'application/javascript'
  only:
  - master
